import Head from 'next/head';
import Home from '~/components/Home/Home';

export default function Index() {
  return (
    <div>
      <Head>
        <title>Shubham Singh | UI Engineer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  );
}
